blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('myblog.urls',namespace='blog')),

]

myblog/urls.py
# encoding: utf-8
"""
@author: yousheng
@contact: 1197993367@qq.com
@site: http://youyuge.cn

@version: 1.0
@license: Apache Licence
@file: urls.py
@time: 17/9/5 下午3:35

"""
from django.conf.urls import url, include
import views

urlpatterns = [
    # 用r'^$'约束空字符串
    url(r'^index/$', views.blog),
    url(r'^article/(?P<article_id>[0-9]+)/$', views.article_page, name='article_page'),
    url(r'^edit/(?P<article_id>[0-9]+)/$', views.edit_page, name='edit_page'),
    url(r'^edit/action/$', views.edit_action, name='edit_action'),
]

myblog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=32,default='title')
    content = models.TextField(default='this is content')
    pub_time = models.DateTimeField(null=True)

    def __unicode__(self):
        return self.title

myblog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
import models


def blog(request):
    articles = models.Article.objects.all()
    return render(request, 'myblog/index.html', {'articles': articles})


def article_page(request, article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'myblog/article_page.html', {'article': article})


def edit_page(request, article_id):
    if str(article_id) == '0':
        return render(request, 'myblog/edit_page.html')
    else:
        article = models.Article.objects.get(pk=article_id)
        return render(request, 'myblog/edit_page.html', {'article': article})


def edit_action(request):
    """
    新增文章逻辑
    :param request:
    :return:
    """
    title = request.POST.get('title')  # 获取表单数据
    content = request.POST.get('content')
    article_id = request.POST.get('article_id', '0')  # 获取隐藏的文章id

    if article_id == '0':  # 新增文章逻辑
        models.Article.objects.create(title=title, content=content)
        articles = models.Article.objects.all()
        return render(request, 'myblog/index.html', {'articles': articles})
    else:  # 修改文章逻辑
        article = models.Article.objects.get(pk=article_id)
        article.title = title
        article.content = content
        article.save()
        return render(request, 'myblog/article_page.html', {'article': article})

myblog/templates/myblog/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>文章标题</title>
</head>
<body>
<h1>{{ article.title }}</h1>
<br/>
<hr/>
<br/>
<h3>{{ article.content }}</h3>
<br/><br/>
<a href="{% url 'blog:edit_page' article.id %}">修改文章</a>
</body>
</html>

myblog/templates/myblog/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改文章</title>
</head>
<body>
<form action="{% url 'blog:edit_action' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="article_id" value="{{ article.id | default:'0' }}">
        <label>文章标题
            <input type="text" name="title" value="{{ article.title }}"/>
        </label>
        <br/>
        <label>文章内容
            <input type="text" name="content" value="{{ article.content }}"/>
        </label>
        <br/>
    <input type="submit" value="提交">
</form>
</body>
</html>

myblog/templates/myblog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>
    <a href="{% url 'blog:edit_page' 0 %}">增加新文章</a>
</h1>
<hr/>
{% for article in articles %}
    <a href="{% url 'blog:article_page' article.id %}">
        {{ article.title }}
    </a>
    <br/>
{% endfor %}
</body>
</html>